# 开启Travis CI任务, 提交后自动生成测试报告。
language: cpp
os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "LI/T3uWMTf2C+MyXt/3eP3hCS2fBHkH8j4IgpsG6nLC02HFgiBuNqak6MLyIswLn69CdxFmy9DpjGKUz7+kxsbgttj/kuUMtSZWwDpdZEj2nAfiZKEkpjesh7fUdGgiTTm/wMY8oOkE3V3H7CWIee6YSkPMUShUqJGtkPyBkRDGqBFnDxIigxgHJA5c4xJLO4QZ3Uuo3q1Ab2aV8mSC0HSM2G9I5z3g+WUzMBW6Ln6yUuKvJmBkjYqdrHGHZcfM5vEg0S0jrMeoeOEOPTY4k23Ejntai+NhOCELNejIO970IMsKIYwrTvi4hWpA7jpd1KUBXjTIpCJvRCG9pChsxSvET3FsFPciclK4cu6qnOOsj5JFJH/mDobPigCaD/nwm0SrkVXIQvHZIhZuv7I194AJYxhLVLQnAgM+7ZEvQehVN2E/wZVSWeDDVtC2xYDJ5tVYIcs5iYTEbUA88N9MXxVorXdZkmu436h+M8qX5WgHO/v/yNzvI18c9pv3Km9Ifcr2x8kCB3/bIo3ZapKnHJWiTHsM0JgaSMcJKjz1FMmvP8xMES9Q0PZadYpiwHmESRaAtq7tVrDHnMGM9Uzff5aY6rH1/N4OIZdfDyCHgFlwC8K3bKgDLUgVckyYBRSQMhwhJhqslA8mKyxzTxCKh93uOsLk8uh0YT+9e0kWppVo="

script: 
  - cd $TRAVIS_BUILD_DIR
  - chmod 755 github-upload.rb
  - echo -e "PSS Test" > liuchao412.txt; 

after_script:
#  - ls -al *.pdf
  - env
  - echo $GITHUB_TOKEN
  - cat liuchao412.txt
#  - ls -al 
# change the name to indicate it is snapshot
# - git config --global github.upload-script-token $GITHUB_TOKEN
  - ./github-upload.rb liuchao412.txt liuchao412/MyCITest --description "generated by travis-ci, $TRAVIS_JOB_ID" --force --name liuchao412.snapshot.txt --skip-ssl-verification -t $GITHUB_TOKEN

