# 开启Travis CI任务, 提交后自动生成测试报告。
language: cpp
os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "pRQ22w5mXxFDcfhPlgajUcQZZ+kVNo2Tm2cqLLvqG1wbUkd4C4oR4YS8j1aMf/sQt+/g+DhJUK55EehkVnLghDI9pIlSQTdCRJRNkPDGE7bsQM50vqTuHSFD7dePiL4eZuUa0Ewi0z1INj5UFArOh/vKNVofpEjvj+hLgBCge9T/MdsitKzGfbKY3IltZYH9LsIn0fGoSYN8kxFd3tU35nusQbTyHdDHUx3U7RQr1xyia+Ap8o6lQUM18OCpiZLyFR4KjcKcsaj+0lMUILSp1tE7PuzlzgE3VwrJjZKJsY6v84wlCe4UEJD8+PWJaNOX2SS59x7U25ShBBvWdmWxLQM/zCyxevy4+1gJd+t/ExbWOFlFtb5ZgkhWTGU4lEkZHjshcNCgqWt8Cdk1/wvMV8p+iTsDo9Fbh6YvMMao/4DwqIgNRqE8Sk5RYoNQ361GpfisGhV1n4Wu2WiDuyaMudHTcWZ2IpeAgd0rerfzg7jCZxrh/2sH8UgO+bLrYgNl83vfUC733Ud7n3CIhYd5gcIVtD4adCEYhDc7eVHRg3+1EDOjewK9+p5eUM4drwnNRt5FTm/p+4zK/iBOUkXT6yM3ETgaiBIZkFLyEo9DcqvGwRvine1oxjbyT+3V357OTswGwGJJmxDCNReEfifRgZKpyAZcc8tzkGGj4EcPFes="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

addons:
  coverity_scan:
    project:
      name: "liuchao412/MyCITest"
      description: "Build submitted via Travis CI"
    notification_email: liuchao412@foxmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: master
